package org.zuel.innovation.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	public void setIsDeleted(java.lang.String isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.String getIsDeleted() {
		return getStr("is_deleted");
	}
	
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}
	
}
