package org.zuel.innovation.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	public void setIsDeleted(java.lang.String isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.String getIsDeleted() {
		return getStr("is_deleted");
	}
	
	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("UserId");
	}
	
	public void setSessionId(java.lang.String SessionId) {
		set("SessionId", SessionId);
	}
	
	public java.lang.String getSessionId() {
		return getStr("SessionId");
	}
	
	public void setType(java.lang.String Type) {
		set("Type", Type);
	}
	
	public java.lang.String getType() {
		return getStr("Type");
	}
	
	public void setSex(java.lang.String Sex) {
		set("Sex", Sex);
	}
	
	public java.lang.String getSex() {
		return getStr("Sex");
	}
	
	public void setIdentity(java.lang.String Identity) {
		set("Identity", Identity);
	}
	
	public java.lang.String getIdentity() {
		return getStr("Identity");
	}
	
}
